export enum ActionType {
  APP_VERSION = 'chain/APP_VERSION',
  FALLBACK_PROVIDER = 'chain/FALLBACK_PROVIDER',
  PROVIDER = 'chain/PROVIDER',
  CHAIN_LOADING = 'chain/CHAIN_LOADING',
  CHAIN_ID = 'chain/CHAIN_ID',
  WEB3_ACTIVE = 'chain/WEB3_ACTIVE',
  CONNECTORS = 'chain/CONNECTORS',
  CONNECTOR = 'chain/CONNECTOR',
  CONTRACT_MAP = 'chain/CONTRACT_MAP',
  ADD_SERIES = 'chain/ADD_SERIES',
  ADD_ASSET = 'chain/ADD_ASSET',
}
