export enum ActionType {
  CHAIN_ID = 'chain/CHAIN_ID',
  CHAIN_LOADING = 'chain/CHAIN_LOADING',
  SERIES_LOADING = 'chain/SERIES_LOADGING',
  STRATEGIES_LOADING = 'chain/STRATEGIES_LOADING',
  EVENTS_LOADING = 'chain/EVENTS_LOADING',
  ASSETS_LOADING = 'chain/ASSETS_LOADING',
  UPDATE_SERIES = 'chain/UPDATE_SERIES',
  UPDATE_STRATEGIES = 'chain/UPDATE_STRATEGIES',
  UPDATE_ASSETS = 'chain/UPDATE_ASSETS',
  UPDATE_EVENTS = 'chain/UPDATE_EVENTS',
  UPDATE_CONTRACT_MAP = 'chain/UPDATE_CONTRACT_MAP',
  RESET = 'chain/RESET',
}
