export enum ActionType {
  UPDATE_CONTRACT_MAP = 'contracts/UPDATE_CONTRACT_MAP',
  UPDATE_EVENT_ARGS_PROPS_MAP = 'contracts/UPDATE_EVENT_ARGS_PROPS_MAP',
  UPDATE_EVENTS = 'contracts/UPDATE_EVENTS',
  EVENTS_LOADING = 'contracts/EVENTS_LOADING',
  UPDATE_ROLES = 'contracts/UPDATE_ROLES',
  ROLES_LOADING = 'contracts/ROLES_LOADING',
  RESET = 'contracts/RESET',
}
